name: keybase
base: core22
version: 6.2.8
summary: Keybase is a chat app
description: Keybase is a chat app

grade: stable
confinement: strict

# TODO: support other architectures
architectures:
  - build-on: amd64

package-repositories:
  # for yarn
  - type: apt
    url: https://dl.yarnpkg.com/debian/
    suites: ["stable"]
    components:
      - "main"
    key-id: 72ECF46A56B4AD39C907BBB71646B01B86E50310

plugs:
  shared-memory:
    private: true
  browser-support:
    allow-sandbox: true

apps:
  Keybase:
    # the arch linux way
    # command: electron usr/share/keybase-app

    # the deb + built from source way of executing
    command: opt/keybase/Keybase
    environment:
      XDG_RUNTIME_DIR: $SNAP_USER_DATA/.config

    extensions: [gnome]
    desktop: usr/share/applications/keybase.desktop
    command-chain:
      # this just sources $SNAP_USER_DATA/.config/keybase/keybase.env
      - setup-env.sh
    plugs:
      - audio-playback
      - network
      - network-bind
      - browser-support
      - unity7

  keybase-cli:
    command: usr/bin/keybase
    plugs:
      - network
      - network-bind
      - home

  keybase-svc:
    command: usr/bin/keybase --debug service
    install-mode: disable
    daemon-scope: user
    daemon: simple
    plugs:
      - network
      - network-bind

  # TODO: fails to start
  # kbfs:
  #   command: usr/bin/kbfsfuse -debug
  #   install-mode: disable
  #   daemon-scope: user
  #   after:
  #     - keybase-svc
  #     # - keybase-redirector
  #   daemon: notify
  #   plugs:
  #     - daemon-notify
  #     - fuse-support
  #     - network
  #     - network-bind
  #     - network-observe # for resolv.conf maybe ?
  #     - mount-observe

  # left as a reference, but not used in the snap since /keybase doesn't work
  # well inside a strict snap
  # keybase-redirector:
  #   passthrough:
  #     install-mode: disable
  #     daemon-scope: user
  #     # from the systemd service, unclear if it's needed
  #     start-command: bin/keybase --use-root-config-file config get --direct --assert-false --assert-ok-on-nil disable-root-redirector
  #   after:
  #     - keybase-svc
  #   command: usr/bin/keybase-redirector /keybase
  #   daemon: simple

parts:
  static:
    source: static
    plugin: dump
    stage-packages:
      - libnss3

  fusermount-with-suid:
    plugin: nil
    stage-packages:
      - fuse
    override-build: |
      # fix suid on fusermount
      chmod 4555 $SNAPCRAFT_PART_INSTALL/bin/fusermount

  keybase:
    source: https://github.com/keybase/client.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    plugin: nil
    build-snaps:
      - go
      - node/20/stable
    build-packages:
      - yarn # from package-repositories
      - unzip
      - rsync
    build-environment:
      - KEYBASE_SKIP_32_BIT: "1"
    override-build: |
      # HACK: the git://github.com links in package.json don't work to build
      # anymore, so we need to use https:// but the tag we are checking out has
      # not been fixed yet, so just patch it here locally to do that change
      sed -i s@git://github.com@https://github.com@g ./shared/package.json
      cd packaging/linux
      ./build_binaries.sh prerelease $SNAPCRAFT_PART_BUILD
      cp -r $SNAPCRAFT_PART_BUILD/binaries/amd64/* $SNAPCRAFT_PART_INSTALL

      # fix suid on chrome-sandbox - note this may not be needed?
      chmod 4555 $SNAPCRAFT_PART_INSTALL/opt/keybase/chrome-sandbox

    override-prime: |
      set -eu
      craftctl default
      # Fix-up application icon lookup
      sed -i.bak -e 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/keybase.png|' usr/share/applications/keybase.desktop
